//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class house_member
    {
        public int Id { get; set; }
        public Nullable<int> houseId { get; set; }
        public string houseUniqueId { get; set; }
        public Nullable<int> userId { get; set; }
        public string userUniqueId { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string houseMemberUniqueId { get; set; }
    }
}
