//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_user
    {
        public int memberId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string firstName_Th { get; set; }
        public string lastName_Th { get; set; }
        public string firstName_En { get; set; }
        public string lastName_En { get; set; }
        public string sex { get; set; }
        public string idCardNo { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string email { get; set; }
        public string cellPhone { get; set; }
        public string homePhone { get; set; }
        public int imageId { get; set; }
        public string imageUniqueId { get; set; }
        public Nullable<int> houseId { get; set; }
        public string houseUniqueId { get; set; }
        public int orgId { get; set; }
        public string orgUniqueId { get; set; }
        public string userRole { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string memberUniqueId { get; set; }
    }
}
