//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_contact
    {
        public int contactId { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<int> locationId { get; set; }
        public string locationUniqueId { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string type { get; set; }
        public string contactUniqueId { get; set; }
    }
}
