//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_house
    {
        public int houseId { get; set; }
        public string name { get; set; }
        public string houseCode { get; set; }
        public int orgId { get; set; }
        public string orgUniqueId { get; set; }
        public int locationId { get; set; }
        public string locationUniqueId { get; set; }
        public int villageId { get; set; }
        public string villageUniqueId { get; set; }
        public int mapId { get; set; }
        public string mapUniqueId { get; set; }
        public int documentId { get; set; }
        public string documentUniqueId { get; set; }
        public int specId { get; set; }
        public string specUniqueId { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string houseUniqueId { get; set; }
        public string houseMappedId { get; set; }
    }
}
