//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_layout
    {
        public int layoutId { get; set; }
        public string layoutUniqueId { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string zone { get; set; }
        public Nullable<int> villageId { get; set; }
        public string villageUniqueId { get; set; }
    }
}
