//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_location
    {
        public int locationId { get; set; }
        public Nullable<int> locationCode { get; set; }
        public string area { get; set; }
        public string subArea { get; set; }
        public string province { get; set; }
        public Nullable<int> zipCode { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string locationUniqueId { get; set; }
    }
}
