//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_village
    {
        public int villageId { get; set; }
        public string name { get; set; }
        public string villageCode { get; set; }
        public Nullable<int> houseAmount { get; set; }
        public int orgId { get; set; }
        public string orgUniqueId { get; set; }
        public int locationId { get; set; }
        public string locationUniqueId { get; set; }
        public int mapId { get; set; }
        public string mapUniqueId { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string villageUniqueId { get; set; }
    }
}
