//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NayooDbEntities : DbContext
    {
        public NayooDbEntities()
            : base("name=NayooDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<house_member> house_member { get; set; }
        public DbSet<med_image> med_image { get; set; }
        public DbSet<med_video> med_video { get; set; }
        public DbSet<mst_contact> mst_contact { get; set; }
        public DbSet<mst_document> mst_document { get; set; }
        public DbSet<mst_event_type> mst_event_type { get; set; }
        public DbSet<mst_house> mst_house { get; set; }
        public DbSet<mst_layout> mst_layout { get; set; }
        public DbSet<mst_location> mst_location { get; set; }
        public DbSet<mst_map> mst_map { get; set; }
        public DbSet<mst_notification_type> mst_notification_type { get; set; }
        public DbSet<mst_organization> mst_organization { get; set; }
        public DbSet<mst_spec> mst_spec { get; set; }
        public DbSet<mst_user> mst_user { get; set; }
        public DbSet<mst_village> mst_village { get; set; }
        public DbSet<opt_event> opt_event { get; set; }
        public DbSet<opt_guest_record> opt_guest_record { get; set; }
        public DbSet<opt_inbox_message> opt_inbox_message { get; set; }
        public DbSet<opt_taxi_call> opt_taxi_call { get; set; }
    }
}
