//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nayoo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class opt_taxi_call
    {
        public int callId { get; set; }
        public string houseNo { get; set; }
        public string houseUniqueId { get; set; }
        public string carLicenseNo { get; set; }
        public string originPlace { get; set; }
        public string destinationPlace { get; set; }
        public System.DateTime callDate { get; set; }
        public System.DateTime readDate { get; set; }
        public int orgId { get; set; }
        public string orgUniqueId { get; set; }
        public string status { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string callUniqueId { get; set; }
        public string description { get; set; }
    }
}
